#touchpanel configuration info
#Fri Nov 15 18:51:44 PST 2024
tpHuntDelay=15000
tpHuntDelayTouched=7000
tpReadDelay=100
tpThreshold=16
tpType=4
tpWatchdogEnable=TRUE
adcPrescaler=9
adcStartup=19
adcSHTime=1
tpMx128=0x001B
tpBx=0x00AF
tpMy128=0x0016
tpBy=0x0EA
tpCalibration=0x00
tpTouchFlipped=both
tpTouchSwap=swapxy
