#pragma once
extern time_t low_clock_time;
extern volatile unsigned char flgADCRead_lADC[8];
extern volatile long ADCRead_lADC[8];
extern volatile unsigned char flgADCZeroRead_lADCZero[8];
extern volatile long ADCZeroRead_lADCZero[8];
extern volatile unsigned char flgServiceChamber_lChamberMax[8];
extern volatile long ServiceChamber_lChamberMax[8];
extern volatile unsigned char flgServiceChamber_lChamberMin[8];
extern volatile long ServiceChamber_lChamberMin[8];
extern volatile unsigned char flgServiceChamber_lADCValue[8];
extern volatile long ServiceChamber_lADCValue[8];
extern volatile unsigned char flgServiceChamber_lChamberValue[8];
extern volatile long ServiceChamber_lChamberValue[8];
extern volatile unsigned char flgServiceChamber_lADCZero[8];
extern volatile long ServiceChamber_lADCZero[8];
extern volatile unsigned char flgChamberVolts_fADCValue[8];
extern volatile float ChamberVolts_fADCValue[8];
extern volatile unsigned char flgChamberVolts_fADCZero[8];
extern volatile float ChamberVolts_fADCZero[8];
extern volatile unsigned char flgChamberVolts_fAppliedADCZero[8];
extern volatile float ChamberVolts_fAppliedADCZero[8];
extern volatile unsigned char flgChamberVolts_fChamberZero[8];
extern volatile float ChamberVolts_fChamberZero[8];
extern volatile unsigned char flgChamberVolts_fAppliedChamberZero[8];
extern volatile float ChamberVolts_fAppliedChamberZero[8];
extern volatile unsigned char flgChamberVolts_fChamberZeroCorr[8];
extern volatile float ChamberVolts_fChamberZeroCorr[8];
extern volatile unsigned char flgChamberVolts_fAppliedChamberZeroCorr[8];
extern volatile float ChamberVolts_fAppliedChamberZeroCorr[8];
extern volatile unsigned char flgChamberVolts_fApplied18Bit[8];
extern volatile float ChamberVolts_fApplied18Bit[8];
extern volatile unsigned char flgChamberVolts_ucGain[8];
extern volatile unsigned char ChamberVolts_ucGain[8];
extern volatile unsigned char flgChamberVolts_fGainFactor[8];
extern volatile float ChamberVolts_fGainFactor[8];
extern volatile unsigned char flgChamberVolts_fAppliedGain[8];
extern volatile float ChamberVolts_fAppliedGain[8];
extern volatile unsigned char flgChamberVolts_fAppliedLinCor[8];
extern volatile float ChamberVolts_fAppliedLinCor[8];
extern volatile unsigned char flgChamberVolts_fChamberBkg[8];
extern volatile float ChamberVolts_fChamberBkg[8];
extern volatile unsigned char flgChamberVolts_fAppliedChamberBkg[8];
extern volatile float ChamberVolts_fAppliedChamberBkg[8];
extern volatile unsigned char flgIsMeas_ucLongAvg[8];
extern volatile unsigned char IsMeas_ucLongAvg[8];
extern volatile unsigned char flgIsMeas_iSampleCount[8];
extern volatile short int IsMeas_iSampleCount[8];
extern volatile unsigned char flgIsMeas_fAverage[8];
extern volatile float IsMeas_fAverage[8];
extern volatile unsigned char flgDisplayActivity_fVolts[9];
extern volatile float DisplayActivity_fVolts[9];
extern volatile unsigned char flgDisplayActivity_fActFact[9];
extern volatile float DisplayActivity_fActFact[9];
extern volatile unsigned char flgDisplayActivity_fResponse[9];
extern volatile float DisplayActivity_fResponse[9];
extern volatile unsigned char flgDisplayActivity_fActivity[9];
extern volatile float DisplayActivity_fActivity[9];
extern volatile unsigned char flgDisplayActivity_fContainerFactor[9];
extern volatile float DisplayActivity_fContainerFactor[9];
extern volatile unsigned char flgDisplayActivity_fAppliedContainerFactor[9];
extern volatile float DisplayActivity_fAppliedContainerFactor[9];

void ClearLowLevel(void);
void PushADCRead(unsigned char ucChamber, long int lADC);
void PushADCZero(unsigned char ucChamber, long int lADCZero);
void PushServiceChamber(unsigned char ucChamber, long lChamberMax, long lChamberMin, unsigned char ucMinFlag, unsigned char ucMaxFlag, long lADCValue, long lChamberValue, long lADCZero);
void PushChamberVolts(unsigned char ucChamber, float fADCValue, float fADCZero, float fAppliedADCZero, float fChamberZero, float fAppliedChamberZero, float fChamberZeroCorr, float fChamberZeroCorrApplied, float fApplied18Bit, unsigned char ucGain, float fGainFactor, float fAppliedGain, float fAppliedLinCor, float fChamberBkg);
void PushChamberVolts2(unsigned char ucChamber, float fAppliedBkg);
void PushIsMeas(unsigned char ucChamber, unsigned char ucLongAvg, short int iSampleCount, float fAverage, float fLinearAverage, float fSquareAverage, float fCubeAverage, unsigned char ucWeighted);
void PushDisplayActivity(unsigned char ucChamber, float fVolts, float fActFact, float fResponse, float fActivity, float fContainerFactor, float fAppliedContainerFactor);
void PushZero(unsigned char ucChamber, float fOpAmpZeroElement);
void SendLowLevelChamber(void);
void SendLowLevelWell(void);
