// Load screen definitions from JSON files generated by the HTM parser
// In production, these are bundled at build time
// During development, they can be loaded from the /screens/ directory

export interface WidgetDef {
  type: string
  name: string
  x: number
  y: number
  width: number
  height: number
  params: Record<string, string>
  position_from?: string
  bindings?: string[]
}

export interface RefreshAction {
  type: string
  target: string
  value?: number | string
}

export interface RefreshTrigger {
  name: string
  interval: string
  onVar: string
  trigger: string
  actions: RefreshAction[]
}

export interface ScreenDef {
  name: string
  filename: string
  resolution: { width: number; height: number }
  widgets: WidgetDef[]
  refreshTriggers: RefreshTrigger[]
  initActions: RefreshAction[]
  referencedImages: string[]
  hasFrenchVariants: boolean
}

const screenCache: Map<string, ScreenDef> = new Map()

export async function loadScreen(name: string): Promise<ScreenDef | null> {
  if (screenCache.has(name)) return screenCache.get(name)!
  try {
    const resp = await fetch(`/screens/${name}.json`)
    if (!resp.ok) return null
    const def: ScreenDef = await resp.json()
    screenCache.set(name, def)
    return def
  } catch {
    return null
  }
}

export async function loadScreenIndex(): Promise<string[]> {
  try {
    const resp = await fetch('/screens/index.json')
    if (!resp.ok) return []
    const index = await resp.json()
    return index.screens?.map((s: any) => s.name) || []
  } catch {
    return []
  }
}
