// Load screen definitions from JSON files generated by the HTM parser
// Screen definitions are served from /screens/ directory
// Screen map maps page index (from firmware) to screen name

export interface WidgetBinding {
  source: string
  type: string
  index: number
  param: string
}

export interface WidgetDef {
  type: string
  name: string
  x: number
  y: number
  width: number
  height: number
  params: Record<string, string>
  position_from?: string
  language?: string
  bindings?: WidgetBinding[]
}

export interface RefreshAction {
  type: string
  target?: string
  value?: number | string
  macro?: string
  args?: string
  expression?: string
}

export interface RefreshTrigger {
  name?: string
  interval?: string
  onVar?: string
  trigger?: string
  actions?: RefreshAction[]
}

export interface StaticImage {
  src: string
  width: number
  height: number
  div_id?: string
}

export interface ScreenDef {
  name: string
  filename: string
  resolution: { width: number; height: number }
  directives?: string[]
  memoryMap?: {
    bytes?: Record<string, string>
    words?: Record<string, string>
    strings?: Record<string, string>
  }
  widgets: WidgetDef[]
  staticImages?: StaticImage[]
  refreshTriggers?: RefreshTrigger[]
  initActions?: RefreshAction[]
  referencedImages?: string[]
  hasFrenchVariants?: boolean
  ramUsage?: Record<string, Record<string, number[]>>
}

// Page index -> screen name mapping
let screenMap: Record<string, string> | null = null
const screenCache: Map<string, ScreenDef> = new Map()

export async function loadScreenMap(): Promise<Record<string, string>> {
  if (screenMap) return screenMap
  try {
    const resp = await fetch('/screen_map.json')
    if (!resp.ok) return {}
    screenMap = await resp.json()
    return screenMap!
  } catch {
    return {}
  }
}

export function getScreenNameForPage(pageIndex: number): string | null {
  if (!screenMap) return null
  return screenMap[String(pageIndex)] || null
}

export async function loadScreen(name: string): Promise<ScreenDef | null> {
  if (screenCache.has(name)) return screenCache.get(name)!
  try {
    const resp = await fetch(`/screens/${name}.json`)
    if (!resp.ok) return null
    const def: ScreenDef = await resp.json()
    screenCache.set(name, def)
    return def
  } catch {
    return null
  }
}

export async function loadScreenByPage(pageIndex: number): Promise<ScreenDef | null> {
  const map = await loadScreenMap()
  const name = map[String(pageIndex)]
  if (!name) return null
  return loadScreen(name)
}
